package util;

public enum SystemMessageType {
    CONNECT,
    DISCONNECT,
    USERNAME_CHANGED,
    USER_DELETED,
    REGULAR_CHAT_DELETED,
    MESSAGE_DELETED,
    REGULAR_CHAT_CREATED,
    INVITE_TO_GROUP_CHAT,
    ADMIN_QUIT_GROUP,
    USER_QUIT_GROUP,
    ADMIN_DELETED_GROUP,
    ADMIN_REMOVED_GROUP_USER,
    GROUP_CHAT_RENAMED
}
